# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Food Recipies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Food Recipies
  pod 'SwiftLint', '~> 0.25'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Alamofire'
  pod 'SDWebImage'


  target 'Food RecipiesTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

  target 'Food RecipiesUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

end
